### ISSUE TITLE
Escrever a premissa do jogo

### ISSUE THREAD

**Issue by bruna-s2001** [mba-studios/mba-studios#1]
5 linhas sobre a premissa do jogo a ser desenvolvido

**Comment by Cadore-ac** [comment]
São 4 personagens iniciais (caso de tempo vamos aumentar para 8), um para cada elemento (água, terra, fogo e ar). A estrutura do jogo, é constituída por fases, onde quanto maior a fase maior o grau de dificuldade, terão fases temáticas para cada elemento (ao todo vamos incluir no jogo 21 fases de início, e aumentaremos conforme a disponibilidade de tempo antes da entrega).

**Comment by bruna-s2001** [comment]
> São 4 personagens iniciais (caso de tempo vamos aumentar para 8), um para cada elemento (água, terra, fogo e ar). A estrutura do jogo, é constituída por fases, onde quanto maior a fase maior o grau de dificuldade, terão fases temáticas para cada elemento (ao todo vamos incluir no jogo 21 fases de início, e aumentaremos conforme a disponibilidade de tempo antes da entrega).

**Comment by bruna-s2001** [comment]
Durante o expediente de trabalho na base nuclear do planeta Gama, houve uma grande explosão, à qual teve forças suficientes para abrir uma fenda no espaço-tempo, formando assim um buraco negro onde alguns operários foram sugados para dentro. Após isso, acabaram chegando em um universo paralelo, e perceberam que, por conta da radiação emitida pela explosão, perceberam que seus corpos haviam sofrido uma mutação, e cada um destes habitantes de Gama se relacionava com um elemento da natureza de seu planeta de origem. 
	Ao chegar no universo paralelo, conhecem uma criatura um tanto grotesca, chamada Byl. Ele é nativo daquela região tão exótica, à qual estranhamente se comunica por telepatia com os visitantes. Sabe dos anseios e desejos, então de prontidão mostra um mapa misterioso, o qual informa que será seu caminho para casa. Mas como sair deste universo paralelo? Byl já não estava mais lá. Deveriam confiar neste contato? Existem muitas dúvidas. Porém, a inércia não pode ser uma opção.
