### ISSUE TITLE
Tocar sons de efeito no jogo

### ISSUE THREAD

**Issue by arthurcadore** [mba-studios/mba-studios#21]
Tarefa em andamento, a aula com a explicação foi postada hoje.

**Comment by arthurcadore** [comment]
Olá, 

Um bug está ocorrendo no gitpod no momento em que um som é adicionado, a tela fica do jogo fica preta e não mostra mais nada, segue abaixo a linha de código comentada: 

![image](https://user-images.githubusercontent.com/74879952/101856511-38b2f800-3b44-11eb-9151-74c833f8b96c.png)

**Comment by ghost** [comment]
São dois argumentos: o nome do objeto e o nome do arquivo. Com as aspas como estão, fica apenas um argumento, por isso o erro.

**Comment by arthurcadore** [comment]
Ok, obrigado prof, correção concluída.

Primeiro som de jogo adicionado: 

Som adicionado, e é executado  no momento em que o personagem pula, segue as imagens para visualização:

![image](https://user-images.githubusercontent.com/74879952/101970773-38316480-3c0b-11eb-96a1-12cc5db8d71d.png)

![image](https://user-images.githubusercontent.com/74879952/101970747-0ae4b680-3c0b-11eb-839d-d08359d6abf9.png)

![image](https://user-images.githubusercontent.com/74879952/101970855-aa09ae00-3c0b-11eb-86f7-2fcf0551fd26.png)

OBS: o som ainda n foi testado pois o gitpod não tem suporte para MP3.
