### ISSUE TITLE
Definir e projetar a tela de encerramento

### ISSUE THREAD

**Issue by arthurcadore** [mba-studios/mba-studios#28]
Olá,

A tela de encerramento ja foi definida e projetada, tanto o código quanto as imagens com a visualização da tela, vão ser postadas posteriormente pela Bruna.

at.te

**Comment by bruna-s2001** [comment]
Cena de encerramento definida, apenas falta fazer alguns ajustes.

Segue imagem da cena
![gameovertela](https://user-images.githubusercontent.com/74878944/101989758-5cc82380-3c81-11eb-89f0-4f151cb41f63.png)

**Comment by Cadore-ac** [comment]
Olá, Tarefa concluida!

A tela de abertura ja foi incluída no código do jogo, e com ajuda do professor, as devidas correções foram realizadas para realizar a passagem de fases. 

Segue em anexo uma print de cada fase:

![image](https://user-images.githubusercontent.com/74879952/102003028-2d490380-3ce1-11eb-9989-6f88afc75ee1.png)
![image](https://user-images.githubusercontent.com/74879952/102003032-34701180-3ce1-11eb-864d-6b2f5bf7115c.png)
![image](https://user-images.githubusercontent.com/74879952/102003035-3c2fb600-3ce1-11eb-8712-569bec848c02.png)
![image](https://user-images.githubusercontent.com/74879952/102003040-42be2d80-3ce1-11eb-84c8-1fc4854f462c.png)

OBS: a mudança de fase é realizada com a tecla "X" devido as mecânicas de mudança de fase ainda não estarem concluidas.

at.te

**Comment by arthurcadore** [comment]
Olá, Tarefa concluida!

A tela de encerramento ja foi incluída no código do jogo, e com ajuda do professor, as devidas correções foram realizadas para realizar a mudança de fases. 

Segue em anexo uma print de cada fase para melhor visualização: 

![image](https://user-images.githubusercontent.com/74879952/102003028-2d490380-3ce1-11eb-9989-6f88afc75ee1.png)
![image](https://user-images.githubusercontent.com/74879952/102003032-34701180-3ce1-11eb-864d-6b2f5bf7115c.png)
![image](https://user-images.githubusercontent.com/74879952/102003035-3c2fb600-3ce1-11eb-8712-569bec848c02.png)
![image](https://user-images.githubusercontent.com/74879952/102003040-42be2d80-3ce1-11eb-84c8-1fc4854f462c.png)

OBS: a mudança de fase é realizada com a tecla "X" devido as mecânicas de mudança de fase ainda não estarem concluídas.

at.te
