### ISSUE TITLE
Impedimento de memória e tela preta

### ISSUE THREAD

**Issue by arthurcadore** [mba-studios/mba-studios#34]
Falar com o professor sobre o código (bruna) para abrir o jogo em nova guia

**Comment by ghost** [comment]
O limite é de memória ou de processamento? No Chrome tem o gerenciador de tarefas, para ver se há algum problema de consumo excessivo. Já viram se pode ser isso?

**Comment by bruna-s2001** [comment]
Abrir jogo em nova guia: python -m http.server 8080

**Comment by ghost** [comment]
Para automatizar o comando no gitpod: https://www.github.com/boidacarapreta/arc20202/tree/main/.gitpod.yml
