### ISSUE TITLE
Redimensionar as imagens de inicio e fim do jogo

### ISSUE THREAD

**Issue by arthurcadore** [mba-studios/mba-studios#35]
Redimensionar as imagens para 600x800 pixels para combinar com as fases do jogo em tela cheia.

**Comment by bruna-s2001** [comment]
A imagem foi redimensionada para o tamanho do canvas (980x735px), porém, a imagem foi cortada por conta do tamanho.
Vou verificar o que pode ser feito para solucionar esse problema.

**Comment by bruna-s2001** [comment]
Imagens redimensionadas para 800x600px.
