### ISSUE TITLE
Aprender JavaScript

### ISSUE THREAD

**Issue by arthurcadore** [mba-studios/mba-studios#4]
Deixar prints nos comentários sobre o desenvolvimento dentro de cursos web sobre JavaScript

**Comment by arthurcadore** [comment]
Tarefa concluída, o curso foi realizado durante o primeiro projeto (classy) da turma, durante esse projeto, participei da area do backend do PeD, então conclui a etapa do curso referente a JavaScript. Segue em anexo a imagem das aulas no site:  

![image](https://user-images.githubusercontent.com/74879952/100255597-726be800-2f22-11eb-82ef-9b0d801b9fc6.png)

**Comment by MatheusPiresSalazar** [comment]
![Screenshot_20201126-121257_Chrome](https://user-images.githubusercontent.com/74925443/100368739-b7575380-2fe2-11eb-80a7-cebf8cd79bb0.jpg)
