### ISSUE TITLE
Realizar curso de Node.js

### ISSUE THREAD

**Issue by bruna-s2001** [mba-studios/mba-studios#40]
O jogo precisará de um servidor para rodar na forma multijogador em rede. Esta tarefa é para realizar o curso ou formação em Node.js ou semelhante que atenda a essa necessidade.

**Comment by bruna-s2001** [comment]
estudo feito

**Comment by MatheusPiresSalazar** [comment]
Estudo finalizado até o vídeo 9 da playlist indicada pelo professor.

**Comment by arthurcadore** [comment]
Estudo finalizado (feito curso ainda no antigo projeto do classy)
