### ISSUE TITLE
Estudar DNS

### ISSUE THREAD

**Issue by bruna-s2001** [mba-studios/mba-studios#43]
Estudar DNS para construção da URL na porção servidor.

Lista de itens a serem estudados citados aqui: https://github.com/boidacarapreta/arc20202/issues/30

**Comment by bruna-s2001** [comment]
Sinalizar aqui quando finalizar o estudo. @MatheusPiresSalazar @Cadore-ac

**Comment by bruna-s2001** [comment]
Estudo finalizado.

**Comment by MatheusPiresSalazar** [comment]
Estudo finalizado.

**Comment by arthurcadore** [comment]
Estudo Finalizado
