### ISSUE TITLE
Definir hospedagem do servidor do jogo

### ISSUE THREAD

**Issue by bruna-s2001** [mba-studios/mba-studios#44]
Definir forma e local de hospedagem do servidor de jogo para que os clientes possam de conectar.

**Comment by arthurcadore** [comment]
Será utilizado o "Heroku" para postagem do jogo, como visto com o professor na aula do dia 11/02

Os endereços utilizados serão adicionados após a definição do nome do jogo, e também após a utilização do Heroku para testes
