### ISSUE TITLE
Criar imagens personalizadas de fundo

### ISSUE THREAD

**Issue by arthurcadore** [mba-studios/mba-studios#56]

**Comment by bruna-s2001** [comment]
Imagens prontas, apenas ainda não foram implementadas. Será feito isso amanhã.

**Comment by bruna-s2001** [comment]
![win2](https://user-images.githubusercontent.com/74878944/115095503-fa658500-9ef7-11eb-890e-1262722752ba.png)
![win3](https://user-images.githubusercontent.com/74878944/115095509-ff2a3900-9ef7-11eb-93cb-fc6f0916c5fe.png)
![tela-de-inicio-td](https://user-images.githubusercontent.com/74878944/115095513-00f3fc80-9ef8-11eb-89cf-70ca3b6f5277.png)
![Uploading win4.png…]()
![gameovertela](https://user-images.githubusercontent.com/74878944/115095520-05201a00-9ef8-11eb-8e2e-3463a8e12134.png)

**Comment by bruna-s2001** [comment]
![win5](https://user-images.githubusercontent.com/74878944/115095528-0a7d6480-9ef8-11eb-8d63-3bc08272edff.png)
![win1](https://user-images.githubusercontent.com/74878944/115095535-0d785500-9ef8-11eb-88b0-6fc20a0f3edd.png)

**Comment by bruna-s2001** [comment]
![win4](https://user-images.githubusercontent.com/74878944/115095577-23861580-9ef8-11eb-83d4-4b68863a1046.png)
