### ISSUE TITLE
Estudar sobre construção de jogos

### ISSUE THREAD

**Issue by arthurcadore** [mba-studios/mba-studios#6]

**Comment by MatheusPiresSalazar** [comment]
abaixo segue a lista de sites e vídeos que estaremos utilizando ao longo do projeto para pegar referencias 
Dicas sobre jogos, montagem de jogos desde história, personagem, músicas e mapas. 
https://www.fabricadejogos.net/  tutoriais de mapas e artigos
https://igf.com/  jogos prontos para se espelhar e artigos sobre jogos
https://blog.saga.art.br/  artigos sobre jogos
https://ed.ted.com/lessons/what-makes-a-hero-matthew-winkler montagem de personagens e história
https://www.youtube.com/c/MarkBrownGMT/featured montagem de história e notícias com dicas sobre jogos
