### ISSUE TITLE
Publicar a versão v1.0 do jogo para computador de mesa 

### ISSUE THREAD

**Issue by arthurcadore** [mba-studios/mba-studios#60]

**Comment by arthurcadore** [comment]
Jogo publicado no servidor, disponivel em: https://elementsofalchemy.boidacarapreta.cc/

**Comment by ghost** [comment]
Falta marcar as tags nos commits correspondentes, conforme os [vídeos da entrega 7](https://www.youtube.com/playlist?list=PLje9mMro7hT2DE6NfFdN-icd9CYqohLuU).

**Comment by arthurcadore** [comment]
Feito!

Publicado em: https://github.com/mba-studios/mba-studios/releases/tag/v1.0.0
