### ISSUE TITLE
Criar sprites para controle por toque na tela 

### ISSUE THREAD

**Issue by arthurcadore** [mba-studios/mba-studios#62]

**Comment by MatheusPiresSalazar** [comment]
Feito, mas ainda não inserido. link para ver prévia: https://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgOCkprXQCQw/view

**Comment by MatheusPiresSalazar** [comment]
Abaixo segue os sprites:
![image](https://user-images.githubusercontent.com/74925443/115096686-9c876c00-9efc-11eb-87e0-a3ae8446d987.png)
![image](https://user-images.githubusercontent.com/74925443/115096700-a610d400-9efc-11eb-888c-c3166e8a0562.png)
![image](https://user-images.githubusercontent.com/74925443/115096710-af01a580-9efc-11eb-9e4e-272af9576508.png)
