### ISSUE TITLE
Publicar a versão v1.1 para dispositivos móveis 

### ISSUE THREAD

**Issue by arthurcadore** [mba-studios/mba-studios#63]

**Comment by arthurcadore** [comment]
Versão publicada, disponivel em: https://elementsofalchemy.boidacarapreta.cc/

**Comment by ghost** [comment]
Falta marcar as tags nos commits correspondentes, conforme os [vídeos da entrega 7](https://www.youtube.com/playlist?list=PLje9mMro7hT2DE6NfFdN-icd9CYqohLuU).

**Comment by arthurcadore** [comment]
Feito!
TAG pode ser acessada no seguinte link: https://github.com/mba-studios/mba-studios/releases/tag/v1.1.0
